name: Build obsidian plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."git@github.com:".insteadOf https://github.com/
      - run: git config --global url."git://".insteadOf https://
      - run: npm ci
      - run: npm run build --if-present
      - run: cp ./styles.css ./obsidian_local_images_plus_latest/styles.css
      - run: zip -r obsidian_local_images_plus_latest.zip ./obsidian_local_images_plus_latest
        shell: bash
      - run: echo "tag_name=$( grep -i '\"version\"' manifest.json | sed -e 's,:, ,g' -e 's,\",,g'  -e 's,\,,,g' -e 's,.* ,,g' )"  >> $GITHUB_ENV
        shell: bash
      - run: echo ${{ env.tag_name }}

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: |
            ./obsidian_local_images_plus_latest.zip
            ./styles.css
            ./manifest.json
            ./obsidian_local_images_plus_latest/main.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}